tasks:
  - name: Install Terraform
    before: |
      echo "Running install terraform script..."
      ./bin/install_terraform_cli
      terraform --version

  - name: utils
    before: |
      echo "Installing utilities..."
      sudo apt-get update
      sudo apt-get install -y tree

  # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
  - name: Install AWS CLI
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      echo "Running install aws script..."
      ./bin/install_aws_cli
      aws --version

  - name: Setup SSH key
    before: |
      echo "Setting up SSH key..."
      if [ ! -f ~/.ssh/gitpod_ec2_key ]; then
        ssh-keygen -t rsa -b 2048 -f ~/.ssh/gitpod_ec2_key -N ""
      fi
      eval $(ssh-agent -s)
      ssh-add ~/.ssh/gitpod_ec2_key
      mkdir -p keys
      cp ~/.ssh/gitpod_ec2_key.pub /keys/gitpod_ec2_key.pub

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform

