tasks:
  - name: Install Terraform
    before: |
      echo "Running install terraform script..."
      ./bin/install_terraform_cli
      terraform --version

  - name: Install Utilities
    before: |
      echo "Installing utilities..."
      sudo apt-get update
      sudo apt-get install -y tree

  - name: Install AWS CLI
    before: |
      echo "Running install aws script..."
      ./bin/install_aws_cli
      aws --version

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform
