tasks:
  - name: Install Terraform
    before: |      
      ./bin/install_terraform_cli
      

  - name: utils
    before: |
      echo "Installing utilities..."
      sudo apt-get update
      sudo apt-get install -y tree

  # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
  - name: Install AWS CLI
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |      
      ./bin/install_aws_cli
      

  - name: Setup SSH key
    before: |
      ./bin/setup_ssh_key

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform

