tasks:
  - name: Install Terraform and utils
    before: |      
      ./bin/install_terraform_cli      

  # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
  - name: Install AWS CLI and set SSH key for AWS environment
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |      
      ./bin/install_aws_cli      

  - name: Setup SSH key for terraform 
    before: |
      ./bin/setup_ssh_key

  


vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform

